server:
  port: 9090
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa 
  jpa:
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'